config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :algorithms
  resources :criterions
  resources :alternatives
  resources :decisions
  
  root 'problems#new'
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

end

app/models/decision.rb
class Decision < ActiveRecord::Base
  belongs_to:criterion
  belongs_to:alternative
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: [:show, :edit, :update, :destroy]

  # GET /decisions
  # GET /decisions.json
  def index
    @decisions = Decision.all
  end

  # GET /decisions/1
  # GET /decisions/1.json
  def show
  end

  # GET /decisions/new
  def new
    @decision = Decision.new
  end

  # GET /decisions/1/edit
  def edit
  end

  # POST /decisions
  # POST /decisions.json
  def create
    @decision = Decision.new(decision_params)

    respond_to do |format|
      if @decision.save
        format.html { redirect_to @decision, notice: 'Decision was successfully created.' }
        format.json { render :show, status: :created, location: @decision }
      else
        format.html { render :new }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decisions/1
  # PATCH/PUT /decisions/1.json
  def update
    respond_to do |format|
      if @decision.update(decision_params)
        format.html { redirect_to @decision, notice: 'Decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @decision }
      else
        format.html { render :edit }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    respond_to do |format|
      format.html { redirect_to decisions_url, notice: 'Decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decision
      @decision = Decision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decision_params
      params.require(:decision).permit(:username, :rating, :comment, :criterion_id, :alternative_id, :agreed_decision_id)
    end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/_form.html.1.erb
<%= form_for(@decision) do |f| %>
  <% if @decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
      <% @decision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :criterion_id %><br>
    <%= f.number_field :criterion_id %>
  </div>
  <div class="field">
    <%= f.label :alternative_id %><br>
    <%= f.number_field :alternative_id %>
  </div>
  <div class="field">
    <%= f.label :agreed_decision_id %><br>
    <%= f.number_field :agreed_decision_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decisions/_form.html.erb
<%= form_for(@decision) do |f| %>
  <% if @decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
      <% @decision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :criterion_id %><br>
    <%= f.number_field :criterion_id %>
  </div>
  <div class="field">
    <%= f.label :alternative_id %><br>
    <%= f.number_field :alternative_id %>
  </div>
  <div class="field">
    <%= f.label :agreed_decision_id %><br>
    <%= f.number_field :agreed_decision_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Editing Decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @decision %> |
<%= link_to 'Back', decisions_path %>

app/views/decisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Decisions</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Rating</th>
      <th>Comment</th>
      <th>Criterion</th>
      <th>Alternative</th>
      <th>Agreed decision</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decisions.each do |decision| %>
      <tr>
        <td><%= decision.username %></td>
        <td><%= decision.rating %></td>
        <td><%= decision.comment %></td>
        <td><%= decision.criterion_id %></td>
        <td><%= decision.alternative_id %></td>
        <td><%= decision.agreed_decision_id %></td>
        <td><%= link_to 'Show', decision %></td>
        <td><%= link_to 'Edit', edit_decision_path(decision) %></td>
        <td><%= link_to 'Destroy', decision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Decision', new_decision_path %>

app/views/decisions/new.html.erb
<h1>New Decision</h1>

<%= render 'form' %>

<%= link_to 'Back', decisions_path %>

app/views/decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @decision.username %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @decision.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @decision.comment %>
</p>

<p>
  <strong>Criterion:</strong>
  <%= @decision.criterion_id %>
</p>

<p>
  <strong>Alternative:</strong>
  <%= @decision.alternative_id %>
</p>

<p>
  <strong>Agreed decision:</strong>
  <%= @decision.agreed_decision_id %>
</p>

<%= link_to 'Edit', edit_decision_path(@decision) %> |
<%= link_to 'Back', decisions_path %>