config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :algorithms
  resources :criterions
  resources :alternatives
  resources :decisions
  
  root 'problems#new'
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
  has_many:problem
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  before_action :set_algorithm, only: [:show, :edit, :update, :destroy]

  # GET /algorithms
  # GET /algorithms.json
  def index
    @algorithms = Algorithm.all
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show
  end

  # GET /algorithms/new
  def new
    @algorithm = Algorithm.new
  end

  # GET /algorithms/1/edit
  def edit
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    @algorithm = Algorithm.new(algorithm_params)

    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully created.' }
        format.json { render :show, status: :created, location: @algorithm }
      else
        format.html { render :new }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algorithms/1
  # PATCH/PUT /algorithms/1.json
  def update
    respond_to do |format|
      if @algorithm.update(algorithm_params)
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully updated.' }
        format.json { render :show, status: :ok, location: @algorithm }
      else
        format.html { render :edit }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm.destroy
    respond_to do |format|
      format.html { redirect_to algorithms_url, notice: 'Algorithm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_algorithm
      @algorithm = Algorithm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def algorithm_params
      params.require(:algorithm).permit(:name)
    end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/views/algorithms/_form.html.erb
<%= form_for(@algorithm) do |f| %>
  <% if @algorithm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@algorithm.errors.count, "error") %> prohibited this algorithm from being saved:</h2>

      <ul>
      <% @algorithm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/algorithms/edit.html.erb
<h1>Editing Algorithm</h1>

<%= render 'form' %>

<%= link_to 'Show', @algorithm %> |
<%= link_to 'Back', algorithms_path %>

app/views/algorithms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Algorithms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @algorithms.each do |algorithm| %>
      <tr>
        <td><%= algorithm.name %></td>
        <td><%= link_to 'Show', algorithm %></td>
        <td><%= link_to 'Edit', edit_algorithm_path(algorithm) %></td>
        <td><%= link_to 'Destroy', algorithm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Algorithm', new_algorithm_path %>

app/views/algorithms/new.html.erb
<h1>New Algorithm</h1>

<%= render 'form' %>

<%= link_to 'Back', algorithms_path %>

app/views/algorithms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @algorithm.name %>
</p>

<%= link_to 'Edit', edit_algorithm_path(@algorithm) %> |
<%= link_to 'Back', algorithms_path %>