config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :algorithms
  resources :criterions
  resources :alternatives
  resources :decisions
  
  root 'problems#new'
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to:problem
end

app/controllers/concerns/criterion.rb
class Criterion
   @@no_of_criteria=0
   attr_reader :id;
   attr_reader :title;
   def initialize(id, title, description)
      @id = id
      @title=title
      @description=description
   end
end

app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :set_criterion, only: [:show, :edit, :update, :destroy]

  # GET /criterions
  # GET /criterions.json
  def index
    @criterions = Criterion.all
  end

  # GET /criterions/1
  # GET /criterions/1.json
  def show
  end

  # GET /criterions/new
  def new
    @criterion = Criterion.new
  end

  # GET /criterions/1/edit
  def edit
  end

  # POST /criterions
  # POST /criterions.json
  def create
    @criterion = Criterion.new(criterion_params)

    respond_to do |format|
      if @criterion.save
        format.html { redirect_to @criterion, notice: 'Criterion was successfully created.' }
        format.json { render :show, status: :created, location: @criterion }
      else
        format.html { render :new }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterions/1
  # PATCH/PUT /criterions/1.json
  def update
    respond_to do |format|
      if @criterion.update(criterion_params)
        format.html { redirect_to @criterion, notice: 'Criterion was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterion }
      else
        format.html { render :edit }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterions/1
  # DELETE /criterions/1.json
  def destroy
    @criterion.destroy
    respond_to do |format|
      format.html { redirect_to criterions_url, notice: 'Criterion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_params
      params.require(:criterion).permit(:title, :description, :priority, :problem_id)
    end
end

app/helpers/criterions_helper.rb
module CriterionsHelper
end

app/views/criterions/_form.html.erb
 

<div id="createCrit">
<div class="row">
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
  <div class="col-sm-10 text-centre label-area">
    <p>Define Criteria</p>
  </div>
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
</div>

<div class="row" id="row-input-crit">
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
  <div class="col-sm-8 text-centre">
    <%#= f.text_field :title %>
    
    <input type="text" class="form-control" id="criterion_title" name="criterion[title]" placeholder="Enter new criterion here..">
    
  </div>
  <div class="col-sm-2 text-centre">
      <div class="btn btn-success btn-lg" id="add-criterion" style="border-radius: 50%">
          <span class="glyphicon glyphicon-plus" ></span>
      </div>
  </div>
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
</div>

<div class="row">
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
  <div class="col-sm-9 text-centre">
    <div class="form-group">
          <%#= f.text_area :description %>
          
          <textarea class="form-control" rows="2" id="criterion_description" name="criterion[description]" placeholder="Enter description of criterion here..."></textarea>
          
        </div>
  </div>
  <div class="col-sm-1 text-centre">
       
  </div>
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
</div>

<div class="row">
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
  <div class="col-sm-4 text-centre label-area">
    <%#= f.label :priority %>
    <label for="criterion_priority">Priority</label>
  </div>
  <div class="col-sm-6 text-centre">
    <%#= f.number_field :priority %>
    <input id="criterion_priority" type="number" name="criterion[priority]">
  </div>
  <div class="col-sm-1 sidenav sidewhite">
    
  </div>
</div>


  
  <div class="row">
      <div class="col-sm-4 sidenav sidewhite">
        <div class="buttons btn btn-danger" id="btnBackToAlternatives">Back</div>
      </div>
      <div class="col-sm-4 text-centre">
        <p></p>
      </div>
      <div class="col-sm-4 sidenav sidewhite">
        <div class="buttons btn btn-success" id="btnToOverview">
          Next
        </div>
      </div>
</div>
  
</div>

app/views/criterions/edit.html.erb
<h1>Editing Criterion</h1>

<%= render 'form' %>

<%= link_to 'Show', @criterion %> |
<%= link_to 'Back', criterions_path %>

app/views/criterions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Criterions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Problem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @criterions.each do |criterion| %>
      <tr>
        <td><%= criterion.title %></td>
        <td><%= criterion.description %></td>
        <td><%= criterion.priority %></td>
        <td><%= criterion.problem_id %></td>
        <td><%= link_to 'Show', criterion %></td>
        <td><%= link_to 'Edit', edit_criterion_path(criterion) %></td>
        <td><%= link_to 'Destroy', criterion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Criterion', new_criterion_path %>

app/views/criterions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', criterions_path %>

app/views/criterions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @criterion.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @criterion.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @criterion.priority %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @criterion.problem_id %>
</p>

<%= link_to 'Edit', edit_criterion_path(@criterion) %> |
<%= link_to 'Back', criterions_path %>