config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :algorithms
  resources :criterions
  resources :alternatives
  resources :decisions
  
  root 'problems#new'
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to:problem
end

app/controllers/alternatives_controller.rb
class AlternativesController < ApplicationController
  before_action :set_alternative, only: [:show, :edit, :update, :destroy]

  # GET /alternatives
  # GET /alternatives.json
  def index
    @alternatives = Alternative.all
  end

  # GET /alternatives/1
  # GET /alternatives/1.json
  def show
  end

  # GET /alternatives/new
  def new
    @alternative = Alternative.new
  end

  # GET /alternatives/1/edit
  def edit
  end

  # POST /alternatives
  # POST /alternatives.json
  def create
    @alternative = Alternative.new(alternative_params)

    respond_to do |format|
      if @alternative.save
        format.html { redirect_to @alternative, notice: 'Alternative was successfully created.' }
        format.json { render :show, status: :created, location: @alternative }
      else
        format.html { render :new }
        format.json { render json: @alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alternatives/1
  # PATCH/PUT /alternatives/1.json
  def update
    respond_to do |format|
      if @alternative.update(alternative_params)
        format.html { redirect_to @alternative, notice: 'Alternative was successfully updated.' }
        format.json { render :show, status: :ok, location: @alternative }
      else
        format.html { render :edit }
        format.json { render json: @alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alternatives/1
  # DELETE /alternatives/1.json
  def destroy
    @alternative.destroy
    respond_to do |format|
      format.html { redirect_to alternatives_url, notice: 'Alternative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alternative
      @alternative = Alternative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alternative_params
      params.require(:alternative).permit(:title, :description, :problem_id)
    end
end

app/controllers/concerns/alternatives.rb
class Alternative
   @@no_of_alternatives=0
   attr_reader :id;
   attr_reader :title;
   def initialize(id, title, description)
      @id=id
      @title=title
      @description=description
   end
end

app/helpers/alternatives_helper.rb
module AlternativesHelper
end

app/views/alternatives/_form.html.erb
<div id="createAlt">
  <div class="row">
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
      <div class="col-sm-10 text-centre label-area">
        <p>Define Alternatives</p>
      </div>
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
</div>

<div class="row" id="row-input">
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
      <div class="col-sm-8 text-centre">
        <%#<%= f.text_field :title %>
        <input id="alternative_title" type="text" class="form-control" name="alternative[title]" placeholder="Enter new alternative here..">
      </div>
      <div class="col-sm-2 text-centre">
          <div href="#" class="btn btn-success btn-lg" id="add-alternative" style="border-radius: 50%">
              <span class="glyphicon glyphicon-plus" ></span>
          </div>
      </div>
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
</div>

<div class="row">
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
      <div class="col-sm-9 text-centre">
        <div class="form-group">
              <%#= f.text_area :description %>
              <textarea class="form-control" rows="2" id="alternative_description" name="alternative[description]" placeholder="Enter description of alternative here..."></textarea>
            </div>
      </div>
      <div class="col-sm-1 text-centre">
           
      </div>
      <div class="col-sm-1 sidenav sidewhite">
        
      </div>
</div>
  
  <div class="row">
      <div class="col-sm-4 sidenav sidewhite">
        <div class="buttons btn btn-danger" id="btnBackToProblem">Back</div>
      </div>
      <div class="col-sm-4 text-centre">
        <p></p>
      </div>
      <div class="col-sm-4 sidenav sidewhite">
        <div class="buttons btn btn-success" id="btnToCriteria">
          Next
        </div>
      </div>
</div>
  
</div>


<%# end %>
  

app/views/alternatives/edit.html.erb
<h1>Editing Alternative</h1>

<%= render 'form' %>

<%= link_to 'Show', @alternative %> |
<%= link_to 'Back', alternatives_path %>

app/views/alternatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alternatives</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Problem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alternatives.each do |alternative| %>
      <tr>
        <td><%= alternative.title %></td>
        <td><%= alternative.description %></td>
        <td><%= alternative.problem_id %></td>
        <td><%= link_to 'Show', alternative %></td>
        <td><%= link_to 'Edit', edit_alternative_path(alternative) %></td>
        <td><%= link_to 'Destroy', alternative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alternative', new_alternative_path %>

app/views/alternatives/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', alternatives_path %>

app/views/alternatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @alternative.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @alternative.description %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @alternative.problem_id %>
</p>

<%= link_to 'Edit', edit_alternative_path(@alternative) %> |
<%= link_to 'Back', alternatives_path %>